name: Rianimazione AREA199 PLAYER
on:
  schedule:
    - cron: "*/15 * * * *" # Esegue ogni 15 minuti
  workflow_dispatch: # Permette il lancio manuale

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Sveglia App Atleta
        run: |
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
          https://area199players.streamlit.app/
